### ISSUE TITLE
How to use MsilAssembler an MsilDisassembler in the new version?

### ISSUE THREAD

**Issue by alex-do** [JerreS/AsmResolver#10]
Hi @JerreS,

Been using v1 for long time and things were quite good. However one day when I upgraded my PC to windows 10, v1 was no longer working. Some stackoverflow error happened in ntdll.dll. Then I updated to v2 and got drowned in the changes. Can you show me how to use MsilAssembler and MsilDisassembler? Let's say I want to get the instructions list of a method from offset A too offset B, then replace some instructions. What I did in v1 was:

```csharp
var assembler = new MSILAssembler(method.Body);
var disassembler = new MSILDisassembler(method.Body);
var instructions = disassembler.Disassemble(0, (int)method.Body.CodeSize);
foreach (var ins in instructions)
    assembler.Replace(ins, MSILInstruction.Create(MSILOpCodes.Nop, null), true);
assembler.Replace(instructions[0], MSILInstruction.Create(MSILOpCodes.Ret, null), true);
method.ApplyChanges();
```

What should I do to achieve the same in v2?

Thanks,
Alex

**Comment by JerreS** [comment]
Hi Alex,

In order to edit MSIL instructions using AsmResolver version 2, you can simply use the `MethodBody.Instructions` property that exposes a collection of `MsilInstruction` instances. You can create an instruction using one of the `MsilInstruction.Create` overloads and use the `Add` or `Insert` method to inject it into the method body. To remove instructions you can simply use the `Remove` method, like any other collection. This is, as you probably can tell, a more high level abstraction of the method body, and takes away the need to use own initialized instances of disassemblers and assemblers, calculating the size of each instruction, replace it with NOPs etc. etc. This is possible since AsmResolver 2 actually uses a more robust PE builder engine which allows the size of the method bodies to be affected. 

```
var body = myMethod.Body;
body.Instructions.Add(...);
body.Instructions.Insert(x, ...);
body.Instructions.Remove(...);
body.Instructions.RemoveAt(x);
// etc.
```

After performing those modifications, it is time to rebuild the application using one of the `WindowsAssembly.Write` overloads.

If, however, you want to use the disassembler and assembler classes yourself, because you want to preserve the size of one method body, or you need to use them somewhere else, you can instantiate a `MsilDisassembler` and `MsilAssembler` yourself using their constructors. 

The disassembler's constructor needs any instance of a `IBinaryStreamReader`, which can be anything that reads the raw bytes, and any instance of a `IOperandResolver`, which resolves the raw operands (raw tokens and instruction references) to actual meaningful operands. 

Take a look at https://github.com/JerreS/AsmResolver/blob/master/AsmResolver/Net/Msil/MethodBody.cs#L174 for an example of how you can use the MsilDisassembler class:

```
...
var disassembler = new MsilDisassembler(_msilReadingContext.Reader, this); // "this" being a MethodBody in this context.
var instructions = disassembler.Disassemble();
...
```

The assembler is pretty much the opposite of the disassembler, and therefore requires an instance of a `IBinaryStreamWriter` to write the bytes to, and an `IOperandBuilder` to format the operand object of an instruction to its byte representation.

Check out https://github.com/JerreS/AsmResolver/blob/master/AsmResolver/Net/Msil/MethodBody.cs#L307 for an example:

```
...
var builder = new MethodBodyOperandBuilder((NetBuildingContext)context.BuildingContext, this); // "this" being a MethodBody in this context.
var assembler = new MsilAssembler(builder, context.Writer);

foreach (var instruction in Instructions)
   assembler.Write(instruction);
...
```

Hope I was clear enough!

Regards,

**Comment by JerreS** [comment]
Since I haven't received any reply for a while, I assume you have figured it out. I'll close this now.
