### ISSUE TITLE
How to create an instruction with TypeReference or FieldReference?

### ISSUE THREAD

**Issue by alex-do** [JerreS/AsmResolver#7]
Hello, World!

Am trying to replace an instruction using MSILAssembler.Replace(). Let's assume that I want to return an empty Guid, how can I create an instruction which refers to System.Guid::Empty field? I tried using MSILInstruction.Create(MSILOpCodes.Ldsfld, 0x0A00013C, assembly.NETHeader) (0x0A00013C was the metadata token I found and the instruction seemed to be successfully created) however I got "System.Guid System.Guid::Empty does not match with the metadata member provided in the target assembly Parameter name: newInstruction".

Any help would be appreciated.

**Comment by JerreS** [comment]
Hi,

I have had several issues with creating and replacing instructions that have member references as operand. This is due to the fact that AsmResolver cannot rebuild applications just yet, and only simple byte patches are possible. This means the member reference should already be present in the member reference metadata table of the application in order to properly use it as an operand. For the time-being, it is not possible yet to add or remove metadata members to the tables without causing trouble ;). 

Now to solve your problem, are you sure the `System.Guid::Empty` field is one of the included references inside the target assembly? If it is, and you are still getting errors, try to use the `Replace(MSILInstruction targetInstruction, MSILInstruction newInstruction, bool overwriteWhenLarger, bool suppressInvalidReferences)` overload instead, and set the surpressInvalidReferences to true like so:

`assembler.Replace(targetInstruction, newInstruction false, true);`

Setting this flag will result in AsmResolver ignoring any metadata references, which is why you should be cautious with it though. Incorrect usage of this flag produces invalid method bodies rather easily. 

Let me know if it worked or not.

P.S: I am actually working on a new version of AsmResolver which uses are more consistent structure, and will (hopefully ;p) be able to rebuild applications to prevent these kinds of errors. So stay tuned for that if you are interested ;).

**Comment by alex-do** [comment]
Hi JerreS,

Thanks for your help.

`System.Guid::Empty` is in `mscorlib` and is already included in my assembly (I believe every single .net assembly uses `mscorlib` as default). however when I turn `suppressInvalidReferences` to true, I got `TOKEN:0000002A` instead of `System.Guid System.Guid::Empty`. It probably caused by incorrect metadata token. Is there any other way to create that instruction? Can we manually create a FieldReference?

By the way, am very glad to here about your new AsmResover. Cant wait to give it a try :+1:

**Comment by JerreS** [comment]
Hi,

I didn't really mean the `mscorlib` assembly reference, but the actual field reference itself. It is not possible to manually add a member reference to the assembly without rebuilding the application, which is unfortunately not supported by this version of AsmResolver.

To check whether the `System.Guid::Empty` field reference is already present in your target assembly, you can open it up in a tool like CFF Explorer or use AsmResolver's preview application. It should look something like this:

![ss 2015-01-28 at 09 53 51](https://cloud.githubusercontent.com/assets/3613449/5946725/4dea0ee4-a738-11e4-8928-bc4bd6f0c407.png)

If you cannot find any item that corresponds with the field you want to refer to, then I am afraid this is not possible just yet with the means of AsmResolver. This will, however, be possible in the new version as I told you in my reply before ;).

Regards

**Comment by alex-do** [comment]
Hi JerreS,

Found that field in my assembly, turns out it has a different metadata token than the one I found. It finally worked like a charm!! Thank you so much!!!

**Comment by JerreS** [comment]
You are welcome. Glad to hear that you got it working ;)

Regards
